### ISSUE TITLE
Some step directory layouts are not handled so that an `undefined.id` error occurs

### ISSUE THREAD

**Issue by aiwilliams** [JupiterOne/integration-sdk#123]
We've seen a good bit of confusion and different directory layouts, and failures only found once deployed, around the loading from a directory structure approach. This mechanism needs to be more robust, or we should consider moving to an explicit `export invocationConfig` from `@jupiterone/graph-*/index.ts`.

**Comment by charlieduong94** [comment]
Given issue #124, the general response to the directory loading approach and the simplicity a single index file brings with publishing/deployment, I don't think it's worth spending time on making the loading more robust.

**Comment by aiwilliams** [comment]
Okay, yah, if we're going to have only the single index solution, then no need to make this work better!
