### ISSUE TITLE
Disable schema validation when deployed to production

### ISSUE THREAD

**Issue by philidem** [JupiterOne/integration-sdk#127]
Since we might not always get complete data back from integration, we should avoid enforcing schema validation when deployed to production environment. Schema validation should only occur when developing and testing integration.

**Comment by aiwilliams** [comment]
@charlieduong94 heads up, maybe you're already aware, but if you do `Closes #127` in your PRs or commit messages, this would get closed, and the project board will automatically move the issue to Done column thanks to the automation on that column.

**Comment by charlieduong94** [comment]
Ahhh that's good to know. Will start doing that going forward.
