### ISSUE TITLE
Improve messaging around steps that fail to be loaded

### ISSUE THREAD

**Issue by charlieduong94** [JupiterOne/integration-sdk#76]
At the moment, the following error is thrown when a step fails to load:
```
TypeError: Cannot read property 'id' of undefined
```

This is a bit cryptic and we should try to improve the messaging around this.

**Comment by aiwilliams** [comment]
@charlieduong94 this will be resolved when step loading is not automatic from directories. I'm supposing you have that on your radar already with other work so I'm closing this, feel free to open if we need it.
